CREATE DATABASE optus;
GO

USE optus;
GO

CREATE TABLE Empresa(
	IdEmpresa INT PRIMARY KEY IDENTITY(1,1),
	NomeEmpresa VARCHAR(20) NOT NULL
);
GO

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY(1,1),
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	NomeUsuario VARCHAR(20) NOT NULL,
	Email VARCHAR(256) NOT NULL,
	Senha VARCHAR(30) NOT NULL,
	TipoPermissao BIT NOT NULL
);
GO

CREATE TABLE Artista(
	IdArtista INT PRIMARY KEY IDENTITY(1,1),
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	NomeArtista VARCHAR(20) NOT NULL,
);
GO

CREATE TABLE Estilo(
	IdEstilo INT PRIMARY KEY IDENTITY(1,1),
	NomeEstilo VARCHAR(16) NOT NULL
);
GO

CREATE TABLE Album(
	IdAlbum INT PRIMARY KEY IDENTITY(1,1),
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista),
	TituloAlbum VARCHAR(50) NOT NULL,
	DataLancamento DATE NOT NULL,
	Localizacao VARCHAR(100) NOT NULL,
	Tempo VARCHAR(10) NOT NULL,
	Visivel BIT NOT NULL
);
GO

CREATE TABLE EstiloAlbum(
	IdEstiloALbum INT PRIMARY KEY IDENTITY(1,1),
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo)
);
GO